[package]
name = "rust-neural-network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
dotenvy = "0.15.7"
rand = "0.8.5"
log = "0.4.20"
